2025-02-23 07:36:31.451141: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1740296191.462616  999240 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1740296191.466165  999240 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-23 07:36:31.729399: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1740296195.482884  999240 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 20732 MB memory:  -> device: 0, name: NVIDIA A10, pci bus id: 0000:25:00.0, compute capability: 8.6
Traceback (most recent call last):
  File "/dcs/21/u2104990/Documents/324/runondcs/run.py", line 117, in <module>
    model.fit(
  File "/dcs/21/u2104990/.local/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/dcs/21/u2104990/.local/lib/python3.12/site-packages/keras/src/layers/input_spec.py", line 227, in assert_input_compatibility
    raise ValueError(
ValueError: Exception encountered when calling Sequential.call().

[1mInput 0 of layer "convnext_small_stem_conv" is incompatible with the layer: expected axis -1 of input shape to have value 3, but received input with shape (None, 64, 64, 1)[0m

Arguments received by Sequential.call():
  â€¢ inputs=tf.Tensor(shape=(None, 64, 64, 1), dtype=float32)
  â€¢ training=True
  â€¢ mask=None
